# Generated by Django 2.2.4 on 2019-08-16 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogador', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogador',
            name='nacionalidade',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
