# Generated by Django 2.2.4 on 2019-08-16 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogador', '0002_auto_20190816_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogador',
            name='imagem',
            field=models.ImageField(upload_to='jogador/'),
        ),
    ]
