# Generated by Django 2.2.4 on 2019-08-16 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regiao', '0003_auto_20190816_1035'),
        ('jogador', '0003_auto_20190816_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogador',
            name='regiao',
            field=models.ManyToManyField(to='regiao.Regiao'),
        ),
    ]
