# Generated by Django 2.2.4 on 2019-08-16 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campeao', '0003_auto_20190816_1537'),
        ('jogador', '0004_jogador_regiao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jogador',
            name='regiao',
        ),
        migrations.AddField(
            model_name='jogador',
            name='campeao',
            field=models.ManyToManyField(to='campeao.Campeao'),
        ),
    ]
