# Generated by Django 2.2.4 on 2019-08-16 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jogador', '0005_auto_20190816_1558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jogador',
            name='campeao',
        ),
    ]
