# Generated by Django 2.2.4 on 2019-08-16 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regiao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regiao',
            name='nome',
            field=models.CharField(max_length=30),
        ),
    ]
