# Generated by Django 2.2.4 on 2019-08-16 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regiao', '0002_auto_20190816_1026'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='regiao',
            options={'ordering': ['nome']},
        ),
    ]
