# Generated by Django 2.2.4 on 2019-08-18 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regiao', '0003_auto_20190816_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='regiao',
            name='slug',
            field=models.SlugField(default='', editable=False, unique=True),
            preserve_default=False,
        ),
    ]
