# Generated by Django 2.2.4 on 2019-08-16 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regiao', '0002_auto_20190816_1026'),
        ('campeonato', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campeonato',
            name='regiao',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='regiao.Regiao'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='campeonato',
            name='nome',
            field=models.CharField(max_length=100),
        ),
    ]
