# Generated by Django 2.2.4 on 2019-08-16 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campeonato', '0002_auto_20190816_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campeonato',
            name='regiao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regiao.Regiao'),
        ),
    ]
