# Generated by Django 2.2.4 on 2019-08-18 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campeonato', '0004_auto_20190816_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='campeonato',
            name='slug',
            field=models.SlugField(default='', editable=False, unique=True),
            preserve_default=False,
        ),
    ]
