# Generated by Django 2.2.4 on 2019-08-16 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campeao', '0002_auto_20190816_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campeao',
            name='imagem',
            field=models.ImageField(upload_to='campeao/'),
        ),
    ]
