# Generated by Django 2.2.4 on 2019-08-16 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jogador', '0006_remove_jogador_campeao'),
        ('campeao', '0003_auto_20190816_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='campeao',
            name='teste',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='jogador.Jogador'),
            preserve_default=False,
        ),
    ]
