# Generated by Django 2.2.4 on 2019-08-16 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campeao', '0006_campeao_teste'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campeao',
            name='teste',
        ),
    ]
