# Generated by Django 2.2.4 on 2019-08-16 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('times', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='times',
            old_name='escudo',
            new_name='imagem',
        ),
    ]
