# Generated by Django 2.2.4 on 2019-08-17 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('times', '0002_auto_20190816_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='times',
            name='abreviatura',
            field=models.CharField(default='', max_length=5),
            preserve_default=False,
        ),
    ]
