# Generated by Django 2.2.4 on 2019-08-18 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('times', '0003_times_abreviatura'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='times',
            options={'ordering': ['nome']},
        ),
    ]
