# Generated by Django 2.2.4 on 2019-08-16 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aovivo', '0002_lance_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lance',
            name='status',
        ),
    ]
