# Generated by Django 2.2.4 on 2019-08-16 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aovivo', '0003_remove_lance_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partida',
            name='lances',
        ),
        migrations.AddField(
            model_name='lance',
            name='partida',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='aovivo.Partida'),
            preserve_default=False,
        ),
    ]
