# Generated by Django 2.2.4 on 2019-08-16 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campeonato', '0004_auto_20190816_1207'),
        ('aovivo', '0005_lance_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='partida',
            name='campeonato',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='campeonato.Campeonato'),
        ),
        migrations.AlterField(
            model_name='lance',
            name='status',
            field=models.CharField(choices=[(0, 'Pré jogo'), (1, 'Em andamento'), (2, 'Jogo Pausado'), (3, 'Pós Jogo'), (4, 'Encerrado')], default=0, max_length=20),
        ),
    ]
