# Generated by Django 2.2.4 on 2019-08-16 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aovivo', '0006_auto_20190816_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='lance',
            name='flyer',
            field=models.ImageField(default='', upload_to='flyer/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lance',
            name='status',
            field=models.IntegerField(choices=[(1, 'Pré jogo'), (2, 'Em andamento'), (3, 'Jogo Pausado'), (4, 'Pós Jogo'), (5, 'Encerrado')], default=1),
        ),
    ]
