# Generated by Django 2.2.4 on 2019-08-16 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aovivo', '0007_auto_20190816_1751'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lance',
            name='flyer',
        ),
        migrations.AddField(
            model_name='partida',
            name='flyer',
            field=models.ImageField(default='', upload_to='flyer/'),
            preserve_default=False,
        ),
    ]
