# Generated by Django 2.2.4 on 2019-08-16 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aovivo', '0008_auto_20190816_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='partida',
            name='descricao',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
