# Generated by Django 2.2.4 on 2019-08-16 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('times', '0002_auto_20190816_1859'),
        ('aovivo', '0010_auto_20190816_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='partida',
            name='blueside',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='bluside', to='times.Times'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partida',
            name='redside',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='redside', to='times.Times'),
            preserve_default=False,
        ),
    ]
