# Generated by Django 2.2.4 on 2019-08-16 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aovivo', '0012_auto_20190816_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='lance',
            name='descricao',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lance',
            name='side',
            field=models.CharField(choices=[(1, 'Blueside'), (2, 'Redside')], default='', max_length=10),
            preserve_default=False,
        ),
    ]
