# Generated by Django 2.2.4 on 2019-08-16 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aovivo', '0013_auto_20190816_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lance',
            name='side',
            field=models.CharField(choices=[(1, 'Blue'), (2, 'Red')], default=1, max_length=10),
        ),
    ]
