# Generated by Django 2.2.4 on 2019-08-16 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aovivo', '0014_auto_20190816_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='partida',
            name='patch',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
