# Generated by Django 2.2.4 on 2019-08-16 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aovivo', '0015_partida_patch'),
    ]

    operations = [
        migrations.AddField(
            model_name='lance',
            name='tempo',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
