# Generated by Django 2.2.4 on 2019-08-16 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aovivo', '0016_lance_tempo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lance',
            name='tempo',
        ),
    ]
