# Generated by Django 2.2.4 on 2019-08-16 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aovivo', '0017_remove_lance_tempo'),
    ]

    operations = [
        migrations.AddField(
            model_name='lance',
            name='tempo',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='lance',
            name='side',
            field=models.CharField(blank=True, choices=[('blue', 'Blue'), ('red', 'Red')], max_length=10),
        ),
    ]
