# Generated by Django 2.2.4 on 2019-08-17 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aovivo', '0019_auto_20190817_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='lance',
            name='link',
            field=models.URLField(default='https://twitter.com/'),
            preserve_default=False,
        ),
    ]
