# Generated by Django 2.2.4 on 2019-08-17 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aovivo', '0020_lance_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lance',
            options={'ordering': ['status']},
        ),
        migrations.AlterField(
            model_name='lance',
            name='link',
            field=models.URLField(blank=True),
        ),
    ]
