# Generated by Django 2.2.4 on 2019-08-17 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aovivo', '0022_auto_20190817_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='lance',
            name='embed',
            field=models.CharField(choices=[('youtube', 'Youtube')], default='', max_length=20),
            preserve_default=False,
        ),
    ]
