# Generated by Django 2.2.4 on 2019-08-17 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aovivo', '0023_lance_embed'),
    ]

    operations = [
        migrations.AddField(
            model_name='lance',
            name='conteudo_embed',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='lance',
            name='embed',
            field=models.CharField(blank=True, choices=[('youtube', 'Youtube')], max_length=20),
        ),
    ]
