# Generated by Django 2.2.4 on 2019-08-18 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aovivo', '0026_partida_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partida',
            name='slug',
        ),
    ]
