# Generated by Django 2.2.4 on 2019-08-18 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aovivo', '0029_auto_20190818_0112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lance',
            name='embed',
            field=models.CharField(blank=True, choices=[('youtube', 'Youtube'), ('twitter', 'Twitter')], max_length=20),
        ),
    ]
