# Generated by Django 2.2.4 on 2019-08-18 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aovivo', '0030_auto_20190818_0227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lance',
            name='embed',
            field=models.CharField(blank=True, choices=[('youtube', 'Youtube'), ('twitch', 'Twitch'), ('twitter', 'Twitter')], max_length=20),
        ),
    ]
