# Generated by Django 2.2.4 on 2019-08-18 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aovivo', '0031_auto_20190818_0235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lance',
            name='descricao',
            field=models.TextField(blank=True),
        ),
    ]
