# Generated by Django 2.2.4 on 2019-08-18 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aovivo', '0032_auto_20190818_0252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partida',
            name='slug',
            field=models.SlugField(editable=False),
        ),
    ]
