# Generated by Django 2.2.4 on 2019-08-18 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aovivo', '0034_lance_stats'),
    ]

    operations = [
        migrations.AddField(
            model_name='partida',
            name='gold_blueside',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partida',
            name='gold_redside',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
