# Generated by Django 2.2.4 on 2019-08-18 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aovivo', '0035_auto_20190818_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partida',
            name='gold_blueside',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='partida',
            name='gold_redside',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='partida',
            name='kill_blueside',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='partida',
            name='kill_redside',
            field=models.IntegerField(default=0),
        ),
    ]
