# Generated by Django 2.2.4 on 2019-08-18 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aovivo', '0036_auto_20190818_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lance',
            name='stats',
            field=models.CharField(blank=True, choices=[('barao|Barão de Nashor', 'Barão de Nashor'), ('dragao-anciao|Dragão ancião', 'Dragão ancião'), ('dragao-infernal|Dragão infernal', 'Dragão infernal'), ('dragao-montanha|Dragão da montanha', 'Dragão da montanha'), ('dragao-oceano|Dragão do oceano', 'Dragão do oceano'), ('dragao-vento|Dragão de vento', 'Dragão de vento')], max_length=20),
        ),
    ]
