# Generated by Django 2.2.4 on 2019-08-18 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aovivo', '0038_auto_20190818_1350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partida',
            name='patch',
        ),
    ]
