# Generated by Django 2.2.4 on 2019-08-18 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aovivo', '0039_remove_partida_patch'),
    ]

    operations = [
        migrations.AddField(
            model_name='lance',
            name='imagem',
            field=models.ImageField(default='', upload_to='lances/'),
            preserve_default=False,
        ),
    ]
