# Generated by Django 2.2.4 on 2019-08-18 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aovivo', '0040_lance_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lance',
            name='imagem',
            field=models.ImageField(blank=True, upload_to='lances/'),
        ),
        migrations.AlterField(
            model_name='lance',
            name='status',
            field=models.IntegerField(choices=[(1, 'Pré jogo'), (2, 'Pick e Bans'), (3, 'Em andamento'), (4, 'Jogo Pausado'), (5, 'Fim de Jogo'), (6, 'Pós Jogo'), (7, 'Encerrado')], default=1),
        ),
    ]
