# Generated by Django 2.2.4 on 2019-08-18 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogador', '0006_remove_jogador_campeao'),
        ('aovivo', '0041_auto_20190818_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='partida',
            name='jogadores_redside',
            field=models.ManyToManyField(related_name='jogadores_redside', to='jogador.Jogador'),
        ),
    ]
