# Generated by Django 2.2.4 on 2019-08-18 22:59

from django.db import migrations, models
import status.models


class Migration(migrations.Migration):

    dependencies = [
        ('aovivo', '0044_remove_partida_jogadores_redside'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lance',
            name='status',
            field=models.IntegerField(default=1, verbose_name=status.models.Status),
        ),
    ]
