# Generated by Django 2.2.4 on 2019-08-20 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aovivo', '0046_auto_20190818_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='partida',
            name='torre_blueside',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='partida',
            name='torre_redside',
            field=models.IntegerField(default=0),
        ),
    ]
