# Generated by Django 2.2.4 on 2019-08-21 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aovivo', '0047_auto_20190820_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lance',
            name='order',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Position'),
        ),
    ]
